spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
     url: jdbc:h2:file:${user.home}/todo/db
     username: default
     password: default
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE